### ISSUE TITLE
Have mscsblog check my ipython for new blog posts

### ISSUE THREAD

**Issue by csawtelle** [gerardramosm89/mscsblog#17]
I want mscs to check my jupyter server in MLHQ folder and post any blog posts it finds in there.

**Comment by csawtelle** [comment]
http://idealistdesign.io/jupyter/tree/MLHQ

**Comment by gerardramosm89** [comment]
hmm.. this one is probably a stretch and we might have to look into this one together.. coz even going into that link to the mlhq posts tree.. requires password, then you have to export it as html from the site right?

probably will require some automation

**Comment by csawtelle** [comment]
they are already on my site in html format

**Comment by csawtelle** [comment]
Giving up on this since its not really valuable
