### ISSUE TITLE
logout automatically if token expires

### ISSUE THREAD

**Issue by csawtelle** [gerardramosm89/mscsblog#20]

**Comment by gerardramosm89** [comment]
Theres two things that is needed for this one right? 

1) Every time you log in and you have a token.. it should extend the timeout period
2) If your token is no longer valid, remove token from localStorage and ask user to log in
3) Also just in addition.. how long should we keep the tokens valid for? @csawtelle

**Comment by csawtelle** [comment]
1.  yea
2.  yea
3.  48 hours probably

**Comment by gerardramosm89** [comment]
jsonwebtoken wouldn't run on the client.

ran around for a while trying to figure out the issue, looks like it's this:
# Missing Net and Dns dependencies in webpack

hapijs/joi#748

placing here for reference

**Comment by gerardramosm89** [comment]
Can now verify by token validity and not just token existence

**Comment by gerardramosm89** [comment]
this one was a doozy. done. closing.
