### ISSUE TITLE
Route should use blog title not ID

### ISSUE THREAD

**Issue by csawtelle** [gerardramosm89/mscsblog#22]
should me mlhq.io/blog/article_title_like_this
instead of mlhq.io/blog/1305842490523

**Comment by gerardramosm89** [comment]
Currently working on this one

Right now we are using the title for the url, we can take the medium approach which to me it looks like they
1) Take the title
2) make it lowercase
3) then append the postId after it

I didn't want to mangle the db and i also opted from adding another attribute to the post object, what I'm going to do is:

From the UI:
1) Create a function that takes a string, in this case will be the title, do what medium does (lower case and replace spaces with '-'), besides append the ID to it. (Which we can do if we want)
2) before rending the route param, run the title through the function, then have it show

domain.com/blog/title-is-this

From server:
1) Server will receive 'title-is-this'
2) Server will remove the dashes and replace them with spaces

Profit. Any concerns let me know @csawtelle

**Comment by gerardramosm89** [comment]
Changes have been uploaded to master on the db and front end servers
