### ISSUE TITLE
Blog post too skinny

### ISSUE THREAD

**Issue by csawtelle** [gerardramosm89/mscsblog#23]
Post should take up 66% of the page, currently is more like 33%

**Comment by csawtelle** [comment]
![image](https://user-images.githubusercontent.com/12061655/28044246-23b45968-658b-11e7-9022-d47dce385609.png)

**Comment by gerardramosm89** [comment]
changed the width to bootstrap col-10, should take care of it bring wider. for any custom changes to it let me know
